apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: apolloai-hml
resources:
  - namespace.yaml
  - ../../base
patches:
  - path: deployment-patch.yaml
labels:
  - pairs:
      app.kubernetes.io/name: apolloai
      app.kubernetes.io/part-of: apollo
