apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: apolloai-hml
resources:
  - namespace.yaml
  - ../../base
  - ingress.yaml
patches:
  - path: configmap-patch.yaml
  - path: deployment-patch.yaml
images:
  - name: ghcr.io/replace-with-owner/apolloai
    newName: ghcr.io/replace-with-owner/apolloai
    newTag: replace-with-commit-sha
labels:
  - pairs:
      app.kubernetes.io/name: apolloai
      app.kubernetes.io/part-of: apollo
